version: '3.8'

services:
  pbb-frontend:
    build:
      context: ./pbb-frontend
      dockerfile: Dockerfile
    container_name: pbb-frontend-prod
    restart: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - pbb-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx-ssl:
    image: nginx:alpine
    container_name: nginx-ssl-prod
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ~/pbb-certs/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      pbb-frontend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    networks:
      - pbb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      timeout: 5s
      interval: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  pbb-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pbb-prod-bridge